project_id = "usxpwndgjlnhbdxxoujf"

[functions.wa-list-instances]
verify_jwt = false

[functions.wa-delete-instance]
verify_jwt = false

[functions.wa-labels]
verify_jwt = false

[functions.wa-contacts]
verify_jwt = false

[functions.wa-public-qrcode]
verify_jwt = false

[functions.check-openai-credits]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.qr-send]
verify_jwt = false

[functions.qr-get-qrcode]
verify_jwt = false
