// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvldqyyzhlygwbgcdqcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bGRxeXl6aGx5Z3diZ2NkcWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MjU0OTUsImV4cCI6MjA3ODMwMTQ5NX0.ykwZak2uz1RX1DiU3zdHCizpmpcWcTavubc9by6eqkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});